### ISSUE TITLE
kkr_scf workflow always continues from last calcs remote even if the previous step was not successful

### ISSUE THREAD

**Issue by PhilippRue** [JuDFTteam/aiida-kkr#10]
Instead of using the last remote folder of the last unsuccesful (e.g. calculation did not converge for some reason an mixing etc is adjusted for next run) calculation the last successful calculation where the convergence behavior was on track should be taken to continue the kkr-scf workflow.

**Comment by fBert31** [comment]
The same problem appears in the `kkr_imp_sub` workflow

**Comment by fBert31** [comment]
Fixed for the `kkr_imp_sub` workflow in commit `8c67fbad68e5c3a4e691793f9ea06512c951c9a3`

**Comment by PhilippRue** [comment]
This was fixed for the bulk scf workflow as well.
