### ISSUE TITLE
maybe change_struc_imp_aux should be a workfunction instead of a simple function

### ISSUE THREAD

**Issue by PhilippRue** [JuDFTteam/aiida-kkr#13]
If we change the definition of the function
https://github.com/JuDFTteam/aiida-kkr/blob/8a2febe8d5dde3c4b6bab5002a34428da4e0f771/aiida_kkr/workflows/kkr_imp.py#L529

to add the `@wf` decorator just before the function definition, aiida should automatically recognize that inputs and outputs are nodes in the database and create the corresponding database nodes with links. This will improve the readability of the workflow afterwards since it makes it clearer to track how input and auxiliary structures are connected.

Here `wf` should be imported like this:
```
from aiida.work.workfunctions import workfunction as wf
```

**Comment by fBert31** [comment]
Fixed in commit `ab13079b08a6061db893856f246c67fe5219f496`
