### ISSUE TITLE
Update tutorial command to aiida version 2

### ISSUE THREAD

**Issue by NihilisticDream99** [JuDFTteam/aiida-kkr#140]
Inside the tutorial the commands are for a previous version of aiida. the command `verdi import` (which is ubiquitous) should be changed to `verdi archive import`. 
Finally the aiida cheat sheet link doesn't work

**Comment by PhilippRue** [comment]
I think this relates to the tutorials from the [judft_tutorials repo](https://github.com/JuDFTteam/judft_tutorials/tree/develop/tutorials/iffaiida_tutorial_01_2020). Please create the issue there.
