### ISSUE TITLE
kkr.py: "# check qdos settings" line 297 looks like a bug

### ISSUE THREAD

**Issue by rkovacik** [JuDFTteam/aiida-kkr#19]
N1 = parameters.get_dict().get('TEMPR')

**Comment by PhilippRue** [comment]
You are right, this line
https://github.com/JuDFTteam/aiida-kkr/blob/df5b8b28b96924db20054a3f69d81356471420a6/aiida_kkr/calculations/kkr.py#L359
should  actually read 
`N1 = parameters.get_dict().get('NPT1')`

**Comment by PhilippRue** [comment]
Fixed with commit 0628b93
