### ISSUE TITLE
use exit codes in workflows

### ISSUE THREAD

**Issue by PhilippRue** [JuDFTteam/aiida-kkr#2]
Use new format of exit codes when workflows are teminated

**Comment by fBert31** [comment]
Also get rid of/change the old way to shut down workchains with the `control_end_wc`, since `self.abort` doesn't work for the new `aiida_core` version

**Comment by PhilippRue** [comment]
The exit codes should also be standardized and be documented

**Comment by PhilippRue** [comment]
Now exit codes are use, but their numbering is not standardized yet. This task has been moved to a new issue (#23).
