### ISSUE TITLE
Serial is always assumed in `start_voro`

### ISSUE THREAD

**Issue by JPchico** [JuDFTteam/aiida-kkr#40]
When running `start_voro` the serial keyword is not explicitly passed via `get_inputs_voronoi`, this in turn results in the `get_inputs_common` setting an option resource dictionary that looks like this
```
        # overwrite settings for serial run
        options['withmpi'] = False
        options['resources'] = {"num_machines": 1}
```

This will fail if one is using a SGE kind of scheduler for the machine where voronoi is compiled.

the simplest solution would be to set

`serial = not self.ctx.withmpi`

```
builder = get_inputs_voronoi(
                    voronoicode, structure, options, label, description, params=params, serial=serial)
```

Unless there is a specific reason for this @PhilippRue , @broeder-j ?

I recognize that in principle one can have voronoi and the host code in two different machines, with two different kinds of schedulers and setups. So perhaps this is a too restrictive approach.

**Comment by PhilippRue** [comment]
The reason for this is that the `voronoi` code is not parallelized and therefore should always run in serial. I am not familiar with the SGE scheduler, so I am not sure what would be the best option here. I assume the SGE scheduler has a problem with the `resources`? I think even if we do
```
builder = get_inputs_voronoi(..., serial=True)
```
we would have the same problem of enforcing a serial run for voronoi which comes from `get_inputs_common`?

**Comment by JPchico** [comment]
Makes sense. The SGE scheduler needs the `parallel_env` line to be able to work, and the `num_machines` actually results in a conflict (it is not supposed to get that input). So this would mean that one would need to detect the scheduler from the code information and then ensure that a minimal information subset is passed. 
I can make a PR for this if that is okay. Plus some minor fixes (_decimation workflow not being present and causing errors in the importing)
What do you think?

**Comment by PhilippRue** [comment]
Sure, go ahead. The `_decimation` import issue should now also be fixed in the `develop` (the file was forgotten in the commit but is now present).

**Comment by JPchico** [comment]
Okay so I think I have done it. I was thinking of adding some examples that use the workchains themselves to show how they work.  Should I add them to the planned PR or do you want me to add them to a new one @PhilippRue ?

**Comment by PhilippRue** [comment]
I think you can also include them in this PR

**Comment by JPchico** [comment]
Through my tests with the scf workchain I found that there are some aspects that are not compatible with `aiida-core==1.4.0` . Namely, the parse uses the method `self.retrieved.open(filename)`, this raises a warning, as one is now supposed to use
```
with self.retrieved.open(filename) as stream:
    ....
```

This should also help the plugin to be more closely compatible with the more up to date aiida releases

**Comment by PhilippRue** [comment]
Is there a place where the changes of commit 9cdfdad62f8e50505a3c6e7bdacc9c9eb5ab0b6e overlooked this?

**Comment by JPchico** [comment]
Damn, realized it was the wrong branch! you are absolutely right it is fine in the develop. Forgot to switch branches in my second vscode window. well that makes it easier =)
