### ISSUE TITLE
Error in finding Bi potential in ElementDataBase

### ISSUE THREAD

**Issue by Sayan611** [JuDFTteam/aiida-kkr#92]
Dear Community,
I am trying a calculation with the material Bi2Se3 but in voronoi step, it's showing an error for Bi potential. The potential for Bi in ElementDataBase is Bi83.genpot and not Bi.pot. The error message is,

 Jellium Potential Read In         1001  points
Generating potential for atom    20 at site    20 with shape     1  
 Using database ....: ElementDataBase/Bi83.pot  
  Error in JELLSTART 
  Potential.............Bi83
  Does not exist in the database

I will be highly obliged if you kindly tell me what to do in such a case.
Thank you.

Regards
Sayan Banik

**Comment by PhilippRue** [comment]
Please check out the `develop` branch of the JuKKR code. Then you will find a starting potential for Bi in the `ElementDataBase`.
