### ISSUE TITLE
"STARTB1:...." error in convergence step

### ISSUE THREAD

**Issue by Sayan611** [JuDFTteam/aiida-kkr#93]
Dear Community,
I am trying to converge a slab calculation in which I am facing this error in the convergence step:

"STARTB1: Error: IRT1P.NE.NR         645         666  for atom          39"

I have attached my input files here. It would be very helpful for me if you kindly help me out.
Thank you.

Regards
Sayan Banik
[Calculation_files.zip](https://github.com/JuDFTteam/aiida-kkr/files/7882156/Calculation_files.zip)

**Comment by PhilippRue** [comment]
For atom 39 the shapefunction radial mesh defined in the shapefun does not match the radial mesh in the potential entry. This is because there is a typo in your inputcard:
```
<ZATOM>  <SHAPE>
...
31.0       33
33.0       34
 0.0       34   <<< should be 35 (see voronoi output file atominfo.txt (NTC column)
 0.0       36
31.0       37
...
```

**Comment by Sayan611** [comment]
I got it. Thank you.

**Comment by Sayan611** [comment]
Dear Phillip,
I want to ask one more thing. When I am working with Bi atom, in voronoi step I am facing error in finding the Bi potential. I saw in ElementDataBase there is Bi83.genpot and not Bi83.pot. The error message is:

Using database ....: ElementDataBase/Bi83.pot  
  Error in JELLSTART 
  Potential.............Bi83
  Does not exist in the database

I will be very grateful if you kindly tell me what to do in such a case.
Thank you.

**Comment by PhilippRue** [comment]
As I said in another issue, you can find it in the develop branch of JuKKR. You can download it from [here](https://iffgit.fz-juelich.de/kkr/jukkr/-/blob/develop/ElementDataBase/Bi83.pot) and put it into your ElementDatabase
